version: "3"
services:
  db:
    image: mysql:5.5.56
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users

  app:
    build: ./app
    ports:
      - "5000:5000"
    links:
      - db